/**
 * Master schema for the HOPE cycle explorer UI.
 * Panel "Input" is split client-side into Editable vs Reference inputs.
 */

export type SchemaItem = {
  metric_key: string;
  panel_key: string;
  panel_order: number;
  item_order: number;
  label: string;
  ui_role: string;
  dtype?: string;
  min?: number;
  max?: number;
  default?: number | string;
  format?: string;
  notes?: string;
};

export const MASTER_SCHEMA = {
  items: [
    // —— Input (split into Editable / Reference) ——
    {
      metric_key: "CR",
      panel_key: "Input",
      panel_order: 0,
      item_order: 10,
      label: "Compression ratio CR",
      ui_role: "input",
      dtype: "number",
      min: 6,
      max: 22,
      default: 12,
      format: "2dp",
    },
    {
      metric_key: "lambda",
      panel_key: "Input",
      panel_order: 0,
      item_order: 20,
      label: "Relative air–fuel ratio λ",
      ui_role: "input",
      dtype: "number",
      min: 0.7,
      max: 1.5,
      default: 1.0,
      format: "2dp",
    },
    {
      metric_key: "rpm",
      panel_key: "Input",
      panel_order: 0,
      item_order: 30,
      label: "Engine speed (rpm)",
      ui_role: "input",
      dtype: "number",
      min: 800,
      max: 6000,
      default: 3000,
      format: "int",
    },
    {
      metric_key: "bore_stroke_ratio",
      panel_key: "Input",
      panel_order: 0,
      item_order: 40,
      label: "Bore / stroke ratio",
      ui_role: "input",
      dtype: "number",
      min: 0.7,
      max: 1.4,
      default: 1.0,
      format: "2dp",
    },
    {
      metric_key: "P1_bar_ref",
      panel_key: "Input",
      panel_order: 0,
      item_order: 50,
      label: "Intake pressure P1 (bar)",
      ui_role: "readonly",
      dtype: "number",
      min: 0.5,
      max: 2,
      default: 1.0,
      format: "2dp",
    },
    {
      metric_key: "T1_C_ref",
      panel_key: "Input",
      panel_order: 0,
      item_order: 60,
      label: "Intake temperature T1 (°C)",
      ui_role: "readonly",
      dtype: "number",
      min: -20,
      max: 60,
      default: 25,
      format: "1dp",
    },
    {
      metric_key: "gamma_ref",
      panel_key: "Input",
      panel_order: 0,
      item_order: 70,
      label: "Polytropic exponent γ (compression)",
      ui_role: "readonly",
      dtype: "number",
      min: 1.2,
      max: 1.45,
      default: 1.33,
      format: "2dp",
    },
    // —— Compression ——
    {
      metric_key: "P1_bar_derived",
      panel_key: "Compression",
      panel_order: 1,
      item_order: 10,
      label: "P1 derived (bar)",
      ui_role: "derived",
      dtype: "number",
      format: "2dp",
    },
    {
      metric_key: "T2_C",
      panel_key: "Compression",
      panel_order: 1,
      item_order: 20,
      label: "T2 end of compression (°C)",
      ui_role: "derived",
      dtype: "number",
      format: "1dp",
    },
    {
      metric_key: "P2_bar",
      panel_key: "Compression",
      panel_order: 1,
      item_order: 30,
      label: "P2 end of compression (bar)",
      ui_role: "derived",
      dtype: "number",
      format: "2dp",
    },
    // —— Pressure & Force ——
    {
      metric_key: "P3_real_bar",
      panel_key: "Pressure & Force",
      panel_order: 2,
      item_order: 10,
      label: "P3 peak pressure (bar)",
      ui_role: "derived",
      dtype: "number",
      format: "2dp",
    },
    {
      metric_key: "P_max_bar",
      panel_key: "Pressure & Force",
      panel_order: 2,
      item_order: 20,
      label: "Pmax indicator (bar)",
      ui_role: "derived",
      dtype: "number",
      format: "2dp",
    },
    // —— Temperature ——
    {
      metric_key: "T3_real_C",
      panel_key: "Temperature",
      panel_order: 3,
      item_order: 10,
      label: "T3 peak gas temperature (°C)",
      ui_role: "derived",
      dtype: "number",
      format: "1dp",
    },
    {
      metric_key: "T_exh_C",
      panel_key: "Temperature",
      panel_order: 3,
      item_order: 20,
      label: "Exhaust gas temperature (°C)",
      ui_role: "derived",
      dtype: "number",
      format: "1dp",
    },
    // —— Heat ——
    {
      metric_key: "Q_in_J",
      panel_key: "Heat",
      panel_order: 4,
      item_order: 10,
      label: "Fuel chemical energy Q_in (J / cycle)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "Q_cool_gross_J",
      panel_key: "Heat",
      panel_order: 4,
      item_order: 20,
      label: "Cooling gross (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "Q_rec_IHRL_J",
      panel_key: "Heat",
      panel_order: 4,
      item_order: 30,
      label: "IHRL recovery (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "Q_cool_net_J",
      panel_key: "Heat",
      panel_order: 4,
      item_order: 40,
      label: "Cooling net loss (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "Q_exh_real_bal_J",
      panel_key: "Heat",
      panel_order: 4,
      item_order: 50,
      label: "Exhaust enthalpy balance (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    // —— Work ——
    {
      metric_key: "W_comp_J",
      panel_key: "Work",
      panel_order: 5,
      item_order: 10,
      label: "Compression work (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "W_exp_real_J",
      panel_key: "Work",
      panel_order: 5,
      item_order: 20,
      label: "Expansion work (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "W_brake_J",
      panel_key: "Work",
      panel_order: 5,
      item_order: 25,
      label: "Brake work equivalent (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "W_net_real_J",
      panel_key: "Work",
      panel_order: 5,
      item_order: 30,
      label: "Net indicated work (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "Q_fric_J",
      panel_key: "Work",
      panel_order: 5,
      item_order: 40,
      label: "Friction losses (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    {
      metric_key: "Q_ub_J",
      panel_key: "Work",
      panel_order: 5,
      item_order: 50,
      label: "Unburned / incomplete (J)",
      ui_role: "derived",
      dtype: "number",
      format: "int",
    },
    // —— Efficiency ——
    {
      metric_key: "eta_brake_pct",
      panel_key: "Efficiency",
      panel_order: 6,
      item_order: 10,
      label: "Brake thermal efficiency η (—)",
      ui_role: "derived",
      dtype: "percent",
      format: "percent_2",
    },
    {
      metric_key: "bsfc_g_kWh",
      panel_key: "Efficiency",
      panel_order: 6,
      item_order: 20,
      label: "BSFC (g/kWh)",
      ui_role: "derived",
      dtype: "number",
      format: "1dp",
    },
    // —— Performance ——
    {
      metric_key: "BMEP_bar",
      panel_key: "Performance",
      panel_order: 7,
      item_order: 10,
      label: "BMEP (bar)",
      ui_role: "derived",
      dtype: "number",
      format: "2dp",
    },
    {
      metric_key: "Power_brake_kW",
      panel_key: "Performance",
      panel_order: 7,
      item_order: 20,
      label: "Brake power (kW)",
      ui_role: "derived",
      dtype: "number",
      format: "2dp",
    },
    // —— Operating Envelope ——
    {
      metric_key: "water_phase_result",
      panel_key: "Operating Envelope",
      panel_order: 8,
      item_order: 10,
      label: "Water phase (HOPE)",
      ui_role: "derived",
      dtype: "text",
    },
    {
      metric_key: "m_water_display",
      panel_key: "Operating Envelope",
      panel_order: 8,
      item_order: 20,
      label: "Water injection mass",
      ui_role: "hidden_value",
      dtype: "text",
    },
  ] as SchemaItem[],
};
